theme: jekyll-theme-minimal
title: Welcome to my space!
description: Hi! My name is Chris, and I'm a SW Developer based in the fairytale city of Marburg, Germany. If you have a project you might need help with just send me a message! I'll try my best to help ğŸ˜
